### ISSUE TITLE
money and all the time show at bottom as transfer when i open inventory

### ISSUE THREAD

**Issue by Qlimqx** [MaDHouSe79/mh-cashasitem#1]
Good morning. from the moment I make a transfer from the bank to have cash. as soon as I open the inventory, I always have the money at the bottom of my inventory which shows me the transfer

do you know where the prob is ?

**Comment by MaDHouSe79** [comment]
check in server file for this

```lua

-- inventory itembox popup when you add or remove items.
local useItemBox = true    -- true if you want to use the itembox popup 
local useAddBox = true     -- true if you want to see the add itembox popup (only works if useItemBox = true)
local useRemoveBox = false -- true if you want to see the remove itembox popup (only works if useItemBox = true)
```
set if to false if you dont want it.

**Comment by Qlimqx** [comment]
[https://imgur.com/a/pnKzp6l](url) i have this porb everytime i have my paychek (i klnow i forgot to add pnj on inventory) but i all time have the same animation for everything

**Comment by MaDHouSe79** [comment]
Again turn off the itembox popup, and it's gone, also you don't have to item image in your inventory image folder.

server/main.lua you need to set it like below all false...
```lua
-- inventory itembox popup when you add or remove items.
local useItemBox = false -- true if you want to use the itembox popup 
local useAddBox = false    -- true if you want to see the add itembox popup (only works if useItemBox = true)
local useRemoveBox = false -- true if you want to see the remove itembox popup (only works if useItemBox = true)
```

**Comment by Qlimqx** [comment]
yeah but like taht i never see the pop up ^^
not possible to see only the pop up when you do the transfer onle and not all time ?

**Comment by MaDHouSe79** [comment]
dude again if you turn that in the mh-cashasitem to false your other itemsboxen will still work.

i close this cause i'm not going to repeat me self over and over again.
