### ISSUE TITLE
cant give cash to players as admin everything else works perfectly

### ISSUE THREAD

**Issue by sabotage93thctv** [MaDHouSe79/mh-cashasitem#11]
cant give cash to players as admin everything else works perfectly and sometime the cash duplicates u cant drop it have to shuffle inventory about then it goes back to normal followed read me 4-5 times :L

**Comment by sabotage93thctv** [comment]
[script:mh-cashasitem] SCRIPT ERROR: @mh-cashasitem-main/server/main.lua:118: attempt to compare number with nil

this is the only error were getting

**Comment by sabotage93thctv** [comment]
we have to use the /givemoney (id) (typeofmoney) (amount) then it works but using /givecash and cookie-adminmenu it says it gives you the money even flases up next to cash amount the amount added but it does not add to them

**Comment by MaDHouSe79** [comment]
@mh-cashasitem-main/server/main.lua:118 that means you do not have this item in your qbcore config.

https://github.com/MaDHouSe79/mh-cashasitem/blob/main/readme.md#note-for-using-blackmoney-as-an-item
if you don't add that it can't count.. ;)

**Comment by sabotage93thctv** [comment]
but now there are no errors that we can see

**Comment by sabotage93thctv** [comment]
use this server side only when you add or delete an item from and to your inventory.
-- true at the end of the trigger is to display money change at the right top of your screen
-- if false you don't see a change but it will change the money amount
TriggerEvent('mh-cashasitem:server:updateCash', src, itemData, amount, "add", true) -- this true

-- true at the end of the trigger is to display money change at the right top of your screen
-- if false you don't see a change but it will change the money amount
TriggerEvent('mh-cashasitem:server:updateCash', src, itemData, amount, "remove", true) -- this true





where/which lua is this added to as im thinking this may not be in but we have redone and followed the steps near 10x lol

**Comment by MaDHouSe79** [comment]
tihs is only server side stuff so also this in server side in the inventory 'inventory:server:SetInventoryData' see the readme folder than qb-inventory, you can see where i put it.

**Comment by sabotage93thctv** [comment]
do you have discord as we cant find where you mean sorry to be a pain
________________________________

**Comment by sabotage93thctv** [comment]
is that the line you mean

________________________________

**Comment by MaDHouSe79** [comment]
you have to look at what that code does, and what the trigger sends from what to where, if you just copy paste it will never work. You have to look in the inventory code to see who does what, where do you remove an item and where do you send it, if you set these triggers the same at that point, it should work, only copy past will not work. you really have to look at my code and pay close attention to what I'm doing, and then you'll see me doing exactly this, see what happens and what goes where.

**Comment by sabotage93thctv** [comment]
this is what i dont under stand which inventory code exactly as there are 4 codes to replace 3 in the same location if i remember right

**Comment by MaDHouSe79** [comment]
but if you don't understand how an inventory works, how can I help you? I'm not going to fully explain to you how an inventory works, this isn't that difficult, it's just moving items, and you have to find the points where you have to place those triggers, I have example codes in the readme folder how you can do this, and if you don't understand this then I don't know how I can help you...

**Comment by sabotage93thctv** [comment]
all we was asking was pointers where to edit a bit more clearly as some bits say add this server side then give no explanation which files to look we can edit our own and figure that out if we know where to look a bit more clearly 🙂
________________________________

**Comment by MaDHouSe79** [comment]
Ye readme says replace the hole code, not parts of it. and if you replace the same TtiggerEvent i say you much replace it sute work. it is really not that hard to do 😄

**Comment by sabotage93thctv** [comment]
lol I’ll reopen it as no support show the community how nice a dev you are
Sent from my iPhone

On 8 Dec 2023, at 17:47, MaDHouSe ***@***.***> wrote:

﻿

Closed #11<https://github.com/MaDHouSe79/mh-cashasitem/issues/11> as completed.

**Comment by MaDHouSe79** [comment]
If we are trying to solve it and you don't say anything, then I assume it has been solved, since everyone does it that way, so you can say you are a nice dev, but if you no longer answer.

**Comment by sabotage93thctv** [comment]
Your the one who told me you could no longer help it’s on your comments
Sent from my iPhone

On 8 Dec 2023, at 20:30, MaDHouSe ***@***.***> wrote:

﻿

If we are trying to solve it and you don't say anything, then I assume it has been solved, since everyone does it that way, so you can say you are a nice dev, but if you no longer answer.

**Comment by MaDHouSe79** [comment]
I don't mean this in a bad way, But again how can I help if someone that doesn't understand how things work?
it takes a lot of time for me, I don't have that time, I'm sorry.
It's a free script, I don't have to give support to people, but I do, but I can't help someone who doesn't know how things work, doesn't know how triggers work and where to put them while I have more example's for you how and where to add it, 
I also have 2 full inventories that work with this script, and still it does not work for you. 

Where is the issue than?, or is that my fault?

**Comment by sabotage93thctv** [comment]
Pull request it is then
Sent from my iPhone

On 9 Dec 2023, at 13:22, MaDHouSe ***@***.***> wrote:

﻿

I don't mean this in a bad way, But again how can I help if someone that doesn't understand how things work?
it takes a lot of time for me, I don't have that time, I'm sorry.
It's a free script, I don't have to give support to people, but I do, but I can't help someone who doesn't know how things work, doesn't know how triggers work and where to put them while I have more example's for you how and where to add it,
I also have 2 full inventories that work with this script, and still it does not work for you.

Where is the issue than?, or is that my fault?

**Comment by MaDHouSe79** [comment]
a pull request for?

**Comment by sabotage93thctv** [comment]
This script as it caused nothing but problems and you won’t even help people with it sus
Sent from my iPhone

On 9 Dec 2023, at 19:41, MaDHouSe ***@***.***> wrote:

﻿

a pull request for?

**Comment by MaDHouSe79** [comment]
I'm not helping... Your Title: **cant give cash to players as admin everything else works perfectly**
Here my anser tor youe question: https://github.com/MaDHouSe79/mh-cashasitem/issues/11#issuecomment-1848409058

I've give you the solution and helpt you, if you don't do anything with it, it's not my problem, is it?

Good day sir.

**Comment by sabotage93thctv** [comment]
You don’t help at all your attitude from day 1 stinks enjoy it being removed from GitHub only dev is meet who’s attitude stinks like shit and is. Not helpful at all your a cunt
Sent from my iPhone

On 9 Dec 2023, at 21:33, MaDHouSe ***@***.***> wrote:

﻿

I'm not helping... Your Title: cant give cash to players as admin everything else works perfectly
Here my anser tor youe question: #11 (comment)<https://github.com/MaDHouSe79/mh-cashasitem/issues/11#issuecomment-1848409058>

I've give you the solution and helpt you, if you don't do anything with it, it's not my problem, is it?

Good day sir.
