### ISSUE TITLE
The script cannot handle money

### ISSUE THREAD

**Issue by Hexney272** [MaDHouSe79/mh-cashasitem#12]
Hello. Many default QBcore script cannot handle money as item. 
Like the qb-customs. I have money in my inventory but the script say: Not enough money
![error](https://github.com/MaDHouSe79/mh-cashasitem/assets/141773707/69dcfb16-7233-4dfc-a498-dd7ae2920789)

**Comment by MaDHouSe79** [comment]
if you type /cash and the same amount is in youre inventory then it sute work, if not you did not install it propperly or you forgot something, it only react on stuff you do when you get or remove money thats it, so your script can work fine with this as long you install everyting that is needed.

**Comment by Hexney272** [comment]
im use your inventory. mh-inventory.

**Comment by MaDHouSe79** [comment]
The script you are using "qb-customs" had nothing to do with `mh-cashasitem`, all other script used the `Player.Functions.AddMoney()` and `Player.Functions.RemoveMoney()` for the item this is the same. but then `AddItem` and `RemoveItem` and `mh-cashasitem` does not use this it react on the hud and the inventory, your script sute work. cause i made it so other scripts don't have to change stuff in code and can use the default that is already there.

and aslong your script uses that functions `the default` functions from `qbcore` itself mh-cashasitem sute work just fine with other scripts, cause if not all other scripts are dependend on this script and that make no cense at all ;)

**Comment by Hexney272** [comment]
okay problem solved. I dont know the problem but the server restart fix it.! Thank you the fast answer.
