### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by IceyDevelopments** [MaDHouSe79/mh-cashasitem#14]
Dose this work with ps-hud

**Comment by MaDHouSe79** [comment]
Hi, yes i think ps-hud work with it, cause this has nothing to do with the cash as item, thats inventory stuff.

Here is the trigger why this script works, it's using the core file player.lua that you also have, if you use qb-core.
Link 1: https://github.com/qbcore-framework/qb-core/blob/b132f2963ee01252eb08b1ed384ad797a7008ff1/server/player.lua#L331

Link 2 : https://github.com/qbcore-framework/qb-core/blob/b132f2963ee01252eb08b1ed384ad797a7008ff1/server/player.lua#L364

Link 3 : https://github.com/qbcore-framework/qb-core/blob/b132f2963ee01252eb08b1ed384ad797a7008ff1/server/player.lua#L384
