### ISSUE TITLE
everything works besides the opening of the inventory

### ISSUE THREAD

**Issue by motrion** [MaDHouSe79/mh-cashasitem#15]
hello i am trying to use this script and everything works except for it doesn't open the inventory when i do /inventory it instead writes this error server sided:

 [    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[ script:ps-inventory] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.

when i add back the default files for ps-inventory it shows that i have my cash in my inventory the only error is that when i am using the code that you provide it cannot open the inventory

**Comment by motrion** [comment]
i would appreciate help as this is something i would love to implement into my server

**Comment by MaDHouSe79** [comment]
I forgot to add this in the readme file, thank for notice.

# Add in ps-inventory/client/main.lua from around line 136
```lua
local function OpenTrunk()
    local vehicle = QBCore.Functions.GetClosestVehicle()
    LoadAnimDict("amb@prop_human_bum_bin@idle_b")
    TaskPlayAnim(PlayerPedId(), "amb@prop_human_bum_bin@idle_b", "idle_d", 4.0, 4.0, -1, 50, 0, false, false, false)
    if IsBackEngine(GetEntityModel(vehicle)) then
        SetVehicleDoorOpen(vehicle, 4, false, false)
    else
        SetVehicleDoorOpen(vehicle, 5, false, false)
    end
end

local function isAllowToOpen(vehicle)
    if GetVehicleClass(vehicle) == 18 then
        if PlayerData.job.name == 'police' or PlayerData.job.name == 'ambulance' then
            return true
        end
    else 
        return true
    end
end
```

**Comment by motrion** [comment]
i appreciate the quick response but unfortunately it still is not working. still writing the same error

[    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[ script:ps-inventory] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.

**Comment by IceyDevelopments** [comment]
Im haveing the same issue where my inventory wont open when i press tab

**Comment by IceyDevelopments** [comment]
Im useing ps inventory

**Comment by MaDHouSe79** [comment]
Ok I looked to see what it could be, but I can't reproduce this error, I don't know how you installed it but I think you forgot something or didn't do something right, because when I install it it just works , this script doesn't work if you only download ps inventory, you have to modify it to make it work with chasasitem. I have an example inventory of ps-inventory and qb-inventory, I also created an mh-inventory because that is the ps-inventory that should work with this script, but it looks like you just dowmload a ps-inventory or uses your old inventory, and then not edit everything that needs to be edited. 

maby here is the issue why it's not opening?

**Comment by fivemNoobDev** [comment]
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/153878827/2eaa07f9-91dd-48c0-96d3-d200c107ab06)
 cant figure it out
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/153878827/9db56f8f-b09a-437d-b04b-2f928a9c5a96)
inventory wont open

**Comment by MaDHouSe79** [comment]
do you have an `Config.UseTarget` in your config?

**Comment by MaDHouSe79** [comment]
> ![image](https://private-user-images.githubusercontent.com/153878827/291097680-2eaa07f9-91dd-48c0-96d3-d200c107ab06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDAzNjcsIm5iZiI6MTcwMjg0MDA2NywicGF0aCI6Ii8xNTM4Nzg4MjcvMjkxMDk3NjgwLTJlYWEwN2Y5LTkxZGQtNDhjMC05NmQzLWQyMDBjMTA3YWIwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QxOTA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTlmMjY1Y2M2MTczMTczNjc0M2IyNDk1Y2I1NDVlNmYxNjRjNTkyODMyZjE3NDg1OTliNWU4Nzc5OGU4MWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d49xnwTqYHKJ-HLOKeRcVZUZ85UgGguxlArmNwGFwN4) cant figure it out ![image](https://private-user-images.githubusercontent.com/153878827/291097715-9db56f8f-b09a-437d-b04b-2f928a9c5a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDAzNjcsIm5iZiI6MTcwMjg0MDA2NywicGF0aCI6Ii8xNTM4Nzg4MjcvMjkxMDk3NzE1LTlkYjU2ZjhmLWIwOWEtNDM3ZC1iMDRiLTJmOTI4YTljNWE5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QxOTA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWUwMWM1OWQ4NjEwYjNjMDNhNDJhYjM5NzlhZDVlZmY3MDQwNDk4ODk5ZDIzYzY1MGViZjdhNjg5OTZiZjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yonmbWbPm3ml1PQdzu3OlGxyiZrrYdFhTz1WeAasUZc) inventory wont open

do you have an `Config.UseTarget` in your config?

**Comment by fivemNoobDev** [comment]
i have no idea this is my first server

**Comment by fivemNoobDev** [comment]
where would that be?

**Comment by MaDHouSe79** [comment]
in `resources\[qb]\qb-inventory/config.lua`

**Comment by fivemNoobDev** [comment]
i had it as false in server.config i changed it to true let me see if that wored

**Comment by fivemNoobDev** [comment]
no did not work same error

**Comment by fivemNoobDev** [comment]
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/153878827/f5f046b5-083d-4526-a8da-c85bbcb9b5b5)
now this
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/153878827/e3f8415f-3944-41d7-aa50-2841a332d122)

**Comment by fivemNoobDev** [comment]
i just want this to work. if it dont imma have to replace all my files i changed for this to work or replace the whole core

**Comment by fivemNoobDev** [comment]
could i swap out the inventory system?

**Comment by fivemNoobDev** [comment]
i switched to mh-inventory and now the inventory opens but no cash item?

**Comment by fivemNoobDev** [comment]
do i have to repeat all the steps for qb-inventory in the configs?

**Comment by MaDHouSe79** [comment]
your config.lua file is not load in, cause the erro `Global Config = nil` means that it does not exsist, i think your config.lua from your inventory is not load in the fxmanifest.lua file.

Example:
```lua
shared_scripts {
    '@qb-core/shared/locale.lua',
    'locales/en.lua',
    'config.lua',
}
```

**Comment by fivemNoobDev** [comment]
your inventory worked. now i have cash as an item!!! thanks for the scripts! now i do have 1 question how do i make the drug selling money into dirty money?

**Comment by fivemNoobDev** [comment]
i use qb-drugs

**Comment by fivemNoobDev** [comment]
thank you got it all to work properly i really appreciate you reply fast with the right information!!!
