### ISSUE TITLE
problem inventory

### ISSUE THREAD

**Issue by mecta02** [MaDHouSe79/mh-cashasitem#16]
Hello, I am having this problem
<img width="631" alt="image" src="https://github.com/MaDHouSe79/mh-cashasitem/assets/17672375/1226a751-0c0e-44d8-ac92-7f2a02b61288">

<img width="784" alt="image" src="https://github.com/MaDHouSe79/mh-cashasitem/assets/17672375/fe07b583-4683-4f33-b3f9-8ad05eaae17f">

sorry for my english

**Comment by MaDHouSe79** [comment]
Check this: https://github.com/MaDHouSe79/mh-cashasitem#to-add-in-your-inventory-configlua-file
I think you forgot something.
