### ISSUE TITLE
it always shows me the itemboxes

### ISSUE THREAD

**Issue by Ol3xi** [MaDHouSe79/mh-cashasitem#17]
Every time I open the inventory it always shows me the added and removed cash itemboxes. As in the photo.
![Screenshot 2023-12-22 221416](https://github.com/MaDHouSe79/mh-cashasitem/assets/101821523/1d5506d9-f547-4778-8b50-823259ba1d9c)

**Comment by MaDHouSe79** [comment]
Check this:https://github.com/MaDHouSe79/mh-cashasitem#check-in-server-file-config

**Comment by Organictuk** [comment]
what if you want the boxes when purchasing something. to show item received and item taken. every-time you open inv. the two cash item pop up

**Comment by MaDHouSe79** [comment]
Thats the part of the inventory, this is only for add/remove money not for items, 
the inventory it self handle the items itembox but not the money, that why you need to set it false so you don't get the box evertime you open/close the inventory, because this script react on that.
