### ISSUE TITLE
inventory issue

### ISSUE THREAD

**Issue by IceyDevelopments** [MaDHouSe79/mh-cashasitem#19]
Im haveing a issue where when i drag
the cash it stuck where e ver i drag it

![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/148407755/65b90a3b-6b33-40ef-8301-a47e06ca25c5)

**Comment by MaDHouSe79** [comment]
It's not a script that you just add and it works, you have to edit a few things before this will work, read the readme file to install it properly, cause you also mis the images.
