### ISSUE TITLE
More a question than issue

### ISSUE THREAD

**Issue by Arkosee** [MaDHouSe79/mh-cashasitem#2]
So we use this currently for our cash (obviously), what I'm wondering is there a way to convert/make another version for dirty money?

Example;

Our drug script gives AddItem(dirty_money) on sale.. 

So we have an "item" dirty money already.. 

What I'm wondering is if a conversion of this is done, would it allow that dirty_money to be used as a currency somehow as I see there are remove functions which I assume work for a store?

Having trouble finding a script we can use for a blackmarket that allows dirty_money (item) to be used as currency and it's a pain lol xD or does this technically not add functionality to stores in any way?

**Comment by Arkosee** [comment]
Nevermind, I think I figured out how to convert it, just need to find a blackmarket script ;)

If you like, I can upload the conversion and you can add it to your scripts so people can have dirty money as an item too :)

**Comment by MaDHouSe79** [comment]
in qb-core dirty money is already an item but with a value on it, so it' s not like cash 1 is 1 no if you have dirty money you get 3 dirty money with a value of maby 10000, you need to wash it to get clean money.
