### ISSUE TITLE
qb-inventory inspired NoPixel

### ISSUE THREAD

**Issue by redycountry** [MaDHouSe79/mh-cashasitem#22]
Hello,

this is actually not a issue but could we get a version for this inventory too which is from qb-inventory but NoPixel inspired. Im already using it but I cant use your script and its just sad.. I was forced to switch back but I would appreciate it if you could look into it ;)

Best regards and thanks anyways for the best script! :)

This is the video and below you can find the GitHub link to download the qb-inventory
[](https://www.youtube.com/watch?v=HgTcbRmhB7Y&t=123s)

**Comment by redycountry** [comment]
https://www.youtube.com/watch?v=HgTcbRmhB7Y&t=123s

**Comment by MaDHouSe79** [comment]
There is no diffrent between this inventorys, this is a qb-inventory that is edit by ps-inventory and this inventory can work with this script. i already made it for the normal qb and ps inventory, just read the readme files what to do to make it work.

**Comment by redycountry** [comment]
I already tried both and both didnt work for me. My inventory is not refreshing means it does not remove the cash from my inventory... 

Which one should work for this NoPixel inventory the readme of ps-inventory?

**Comment by MaDHouSe79** [comment]
I just check the inventory in the video and it's the same code as ps-invnetory, the only diffrfend is the layout?

and you need the qb-hud to trigger the OnMoneyChange trigger to make this script work on that, so you need to edit a lot befor it works 😄

**Comment by redycountry** [comment]
Yes seems like there is some changes needed, like if I drop/drag my money it doesnt remove/add etc :D 

Do you mind if we could meet on discord or somewhere to do it together ? I will test it then till it works and after it works 100% you can publish it for your community as well :)

**Comment by MaDHouSe79** [comment]
I don't have discord sorry, but in the readme.md file you see what you need to change and edit for the ps-inventory, if you don't do that, this script will not work, it's not just a copy past script, you need to edit your own scripts if you want to add this script to your server, so you need to edit your qb-hud you need to edit qb-core and you need to edit your ps-inventory and all that you can find in the readme file where and what to do and change 😄
