### ISSUE TITLE
MONEYWASH

### ISSUE THREAD

**Issue by stewiemc1991** [MaDHouSe79/mh-cashasitem#23]
I'm with qb-core and it's a complete pain to was the money I've looked kard and tried to convert from markedbills to blackmoney for washing but it doesn't come out the inventory,  is there possible chance making your own version that washes blackmoney instead of markedbills and actually removes it from your inventory

**Comment by MaDHouSe79** [comment]
The only difference in these 2 items is, 
the blackmoney uses the item amount as a number, 
and the marketbills uses the item mount as a table.

so you need to edit that part of the code.
from this 
```lua
local worth = {value=10} -- table
Player.Functions.AddItem('marketbills', worth) -- to add marketbills

Player.Functions.RemoveItem('marketbills', worth)-- to remove marketbills
```
to this
 ```lua
local amount = 10 -- number
Player.Functions.AddItem('blackmoney', amount) -- to add blackmoney

Player.Functions.RemoveItem('blackmoney', amount)  -- to remove blackmoney
```

**Comment by stewiemc1991** [comment]
Where does this code go

**Comment by MaDHouSe79** [comment]
give me your script than i put it in for you.

**Comment by stewiemc1991** [comment]
Sorry which scriptnare you requesting? Money wash or your cashasitem

**Comment by MaDHouSe79** [comment]
your moneywash script so i can show you where to change it.

**Comment by stewiemc1991** [comment]
or if u have another money wash thts good for it

**Comment by MaDHouSe79** [comment]
See if this works for you, https://github.com/MaDHouSe79/mh-moneywash
