### ISSUE TITLE
Attemt to compare with nill value

### ISSUE THREAD

**Issue by MamBa-OP** [MaDHouSe79/mh-cashasitem#24]
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/69965743/e6b56e19-b31a-4864-bacb-40c1f8d80b80)

**Comment by MaDHouSe79** [comment]
when does this happen cause it looks like you have no monay in your inventory,

Error line in the script:https://github.com/MaDHouSe79/mh-cashasitem/blob/795a551517a89e1790246422e6977b3f817efdbd/server/main.lua#L45
