### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by lazerrwolf** [MaDHouSe79/mh-cashasitem#26]
Can you help me figure out what is causing this error? 
Script seems to be working fine but i'm getting this error. and also here is my server/main.lua as it is

![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/142634910/c9505284-c71b-4f23-8873-3b1bba22ed05)

![error](https://github.com/MaDHouSe79/mh-cashasitem/assets/142634910/257931ce-e5e2-4c4a-8719-3fb34c5f0565)

**Comment by MaDHouSe79** [comment]
download a new one and try again, i just update the code. 😄
