### ISSUE TITLE
Problems with money drops

### ISSUE THREAD

**Issue by web-caos** [MaDHouSe79/mh-cashasitem#27]
Everytime i try to drop money and then get them back i get this error:
SCRIPT ERROR: @qb-inventory/server/main.lua:989: attempt to index a nil value (field '?')
And money still dropped
Any idea?

**Comment by xamixami471** [comment]
set in your qb-core/config.lua on line 9 and 10 like this :
QBConfig.Money = {}
QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0, blackmoney = 0 }
QBConfig.Money.DontAllowMinus = { 'cash', 'crypto', 'blackmoney' }

**Comment by MaDHouSe79** [comment]
do you use a default qb-core? with the default scripts?

**Comment by LaceUpBrah** [comment]
Hi. I'm having the exact same issue..

**Comment by LaceUpBrah** [comment]
> do you use a default qb-core? with the default scripts?

Hi. I'm having the exact same issue but for me it happens every time I open the inventory.

![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/109901109/fab2b496-fd67-4564-9cbb-af22d1d5bed1)

It says that this right here is the issue but I've followed your tutorial, everything works fine expect this console error.

![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/109901109/086c6adb-0317-437d-8643-025cccd45044)

**Comment by MaDHouSe79** [comment]
> > do you use a default qb-core? with the default scripts?
> 
> Hi. I'm having the exact same issue but for me it happens every time I open the inventory.
> 
> ![image](https://private-user-images.githubusercontent.com/109901109/306908829-fab2b496-fd67-4564-9cbb-af22d1d5bed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODgxNDEsIm5iZiI6MTcwODU4Nzg0MSwicGF0aCI6Ii8xMDk5MDExMDkvMzA2OTA4ODI5LWZhYjJiNDk2LWZkNjctNDU2NC05Y2JiLWFmMjJkMWQ1YmVkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwNzQ0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDJmOTBkNTIyNTQxYmM4MDlhZDcwYjAzZjExZjVkOTJlZDE3MDQ2NWE4ZThlMmQwM2I0OGEwODIzOGU1OWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k2YhzEow8ws553FzfeWLBBUNBRwUvUfvbJuJVsn5i20)
> 
> It says that this right here is the issue but I've followed your tutorial, everything works fine expect this console error.
> 
> ![image](https://private-user-images.githubusercontent.com/109901109/306909113-086c6adb-0317-437d-8643-025cccd45044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODgxNDEsIm5iZiI6MTcwODU4Nzg0MSwicGF0aCI6Ii8xMDk5MDExMDkvMzA2OTA5MTEzLTA4NmM2YWRiLTAzMTctNDM3ZC04NjQzLTAyNWNjY2Q0NTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwNzQ0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjcxYmMzMGI0Y2Q1OWY0Njg1ODE1ODUwYmQyYjljMzlhMGRjYTk4ODQwYTMxMjNhYmUyMzNkYjVjYWI2MDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZOmJ32oJruqwWEgGmvhmfTu6YjlBQVGWHE0wfcs1QH8)

Do you have the item in your inventory? cause it looks like the cash is nil and why this is not a number.


Add on line 40 above the if count >=1 and cash >=1 then print(itemCount, cash)

```lua
print(itemCount, cash) -- <-- Add Here
if itemCount >= 1 and cash >= 1 then
    ItemBox(lastItem, Player, itemCount, "remove")
    AddItem(moneyType, Player, cash, lastSlot)
elseif itemCount <= 0 and cash >= 1 then
    AddItem(moneyType, Player, cash, lastSlot)
end
```

if that gives a nil then try to replace the function with this function,
and see if that works for you.

```lua
local function UpdateCashItem(src, moneyType)
    local Player = QBCore.Functions.GetPlayer(src)
    if Player then
        local cash = Player.Functions.GetMoney(moneyType)
        local itemCount, lastSlot, lastItem = 0, nil, nil
        for _, item in pairs(Player.PlayerData.items) do
            if item and item.name:lower() == moneyType then
                itemCount = itemCount + item.amount
                lastSlot = item.slot
                lastItem = item.name
                Player.Functions.RemoveItem(item.name, item.amount, item.slot)
            end
        end
        if type(itemCount) == 'number' and type(cash) == 'number' then -- << add
            if itemCount >= 1 and cash >= 1 then
                ItemBox(lastItem, Player, itemCount, "remove")
                AddItem(moneyType, Player, cash, lastSlot)
            elseif itemCount <= 0 and cash >= 1 then
                AddItem(moneyType, Player, cash, lastSlot)
            end
        end -- << add
    end
end
```

**Comment by LaceUpBrah** [comment]
> if that gives a nil then try to replace the function with this function, and see if that works for you.
> 
> ```lua
> local function UpdateCashItem(src, moneyType)
>     local Player = QBCore.Functions.GetPlayer(src)
>     if Player then
>         local cash = Player.Functions.GetMoney(moneyType)
>         local itemCount, lastSlot, lastItem = 0, nil, nil
>         for _, item in pairs(Player.PlayerData.items) do
>             if item and item.name:lower() == moneyType then
>                 itemCount = itemCount + item.amount
>                 lastSlot = item.slot
>                 lastItem = item.name
>                 Player.Functions.RemoveItem(item.name, item.amount, item.slot)
>             end
>         end
>         if type(itemCount) == 'number' and type(cash) == 'number' then -- << add
>             if itemCount >= 1 and cash >= 1 then
>                 ItemBox(lastItem, Player, itemCount, "remove")
>                 AddItem(moneyType, Player, cash, lastSlot)
>             elseif itemCount <= 0 and cash >= 1 then
>                 AddItem(moneyType, Player, cash, lastSlot)
>             end
>         end -- << add
>     end
> end
> ```


My man, you just fixed the issue. No more errors and everything works as it should. 
You're the best! Thank you.
