### ISSUE TITLE
Issue With blackmoney

### ISSUE THREAD

**Issue by Brave-developments** [MaDHouSe79/mh-cashasitem#28]
I followed entire steps correct and the cash item is working fine. But When i do robbery i still get the market bills + when i try to give myself blackmoney through /give .. it shows in hud but wont appear in inventory. 

Also i havent figured where this is 
local worth = {value=10} -- table
Player.Functions.AddItem('marketbills', worth) -- to add marketbills
Player.Functions.RemoveItem('marketbills', worth)-- to remove marketbills

**Comment by MaDHouSe79** [comment]
you need to add the items in `shared items`, you also need to edit scripts that you want to use `black_money` but this script now uses `marketbills`, you can use the `example` from the readme to change that to `black_money`.

If the item is not in the qb shared or qb-inventory images, the items does not work.

also the `blackmoney` item is now `black_money` cause some other inventorys uses that as item name.

**Comment by Brave-developments** [comment]
Thanks Mate. That was very helpful. And the item didn't show up because black money was considered currency so "Setmoney blackmoney" worked. 💕

**Comment by Brave-developments** [comment]
If you have a discord i am happy to join.

**Comment by MaDHouSe79** [comment]
no i don't use that anymore sorry.
