### ISSUE TITLE
Attempt to call a nil value

### ISSUE THREAD

**Issue by benjibrew** [MaDHouSe79/mh-cashasitem#3]
Hello! :)
I implemented mh_inventory and mh_cashasitem exactly as its told in the readme files but I get the following 2 errors in my server console when updating the cash item via opening the inventory (all stock qbcore).

SCRIPT ERROR: @mh-cashasitem/server/main.lua:47: attempt to call a nil value (global 'RemoveItem‘)

SCRIPT ERROR: @mh-cashasitem/server/main.lua:54: attempt to call a nil value (global 'AddItem‘)

Did I do something wrong? When I´m adding the cash item manually to my inventory and removing it the cash value gets updated as it should.

Sorry for the support request.

**Comment by MaDHouSe79** [comment]
i see, if you get the code from the server file here, i just update it, try if it works now ;)

**Comment by benjibrew** [comment]
You are a god. <3
