### ISSUE TITLE
DRC Scripts Needs Your Input

### ISSUE THREAD

**Issue by KK7130** [MaDHouSe79/mh-cashasitem#30]
Hello MaDHouSe79,

I am currently working with DRC Scripts with their money wash script and they are trying to figure out how to properly have their code remove the dirtymoney cash item from your script so that it is not duplicating money within their script. They asked me to reach out to you to see if you could assist with fixing their code to function properly with the mh-cashasitm. I would greatly appreciate it if you could assist us all.

**Comment by MaDHouSe79** [comment]
if you want to add or remove cash or black_money just use the default qbcore functions. 

```lua
QBCore.Functions.AddMoney('black_money', 100)
QBCore.Functions.RemoveMoney('black_money', 100)
```
