### ISSUE TITLE
[mh-cashasitem-main] Check for script update FAILED

### ISSUE THREAD

**Issue by redbull196** [MaDHouSe79/mh-cashasitem#31]
HI, 

Im trying to run this script on Qb corer but i keep getting the following error when i try to run it 

[mh-cashasitem-main] Check for script update FAILED 

I have placed it below my [standalone] as per the instructions. Also the cash isnt actually showing up in my inventory

**Comment by MaDHouSe79** [comment]
rename the folder from `mh-cashasitem-main` to `mh-cashasitem` and try again, never use the `-main` in the folder name. 😃 

check here: https://github.com/MaDHouSe79/mh-cashasitem?tab=readme-ov-file#install

**Comment by redbull196** [comment]
Thanks, that worked! although it dont start automatically

**Comment by MaDHouSe79** [comment]
you need to add `ensure mh-cashasitem` on the right spot in your `server.cfg` to start it automatically.
