### ISSUE TITLE
ps-hud

### ISSUE THREAD

**Issue by TungPunchMe** [MaDHouSe79/mh-cashasitem#32]
is there anyway this could be used for ps-hud ? and also i have nothing come up when i go to the washing machines around the map but that could be a case of not being able to do the last two steps for the hud im not sure

**Comment by MaDHouSe79** [comment]
ps hud can work if you edit this 

https://github.com/Project-Sloth/ps-hud/blob/6d394735e95c5ce5d552c88b1d4494b2de52d5eb/client.lua#L1054

and

https://github.com/Project-Sloth/ps-hud/blob/6d394735e95c5ce5d552c88b1d4494b2de52d5eb/client.lua#L1070

this is uses to work with mh-cashasitem also ps-inventory can work with it.

**Comment by TungPunchMe** [comment]
yeah i changed these but it still wont register black_money as an item, i can give it to myself through admin but it wont come up in my inventory nor can i use it at the laundry, I'm still  using qb-inventory.

after doing this i cant get my bank to appear in the right or my cash.. if i could get black_money as just an item it would be fine but it isn't working like that unfortunately

**Comment by MaDHouSe79** [comment]
You can ask ps-hud owner if he can add a black_money item, cause cash is the same, you can try that

**Comment by TungPunchMe** [comment]
RegisterNetEvent('hud:client:ShowAccounts', function(type, amount)
    if type == 'cash' then
        SendNUIMessage({
            action = 'show',
            type = 'cash',
            cash = amount
        })
        
        this is the issue i am having because i the opening bracket after registernetevent is red and i dont know how to fix that

**Comment by MaDHouSe79** [comment]
In ps-hud you need to edit 3/4 files with this
https://github.com/MaDHouSe79/mh-cashasitem/blob/main/readme/qb_hud.md

The only thing is i can't add it, cause the js file from ps-hud is compressed, so you need yo ask the owner that build that script to add black_money to the system so it can work with it, if he don't do that is will not work.

**Comment by MaDHouSe79** [comment]
> RegisterNetEvent('hud:client:ShowAccounts', function(type, amount) if type == 'cash' then SendNUIMessage({ action = 'show', type = 'cash', cash = amount })
> 
> ```
>     this is the issue i am having because i the opening bracket after registernetevent is red and i dont know how to fix that
> ```

see here i already ask him,
https://github.com/Project-Sloth/ps-hud/issues/113

**Comment by TungPunchMe** [comment]
thanks mate i seen that he done this now i can get black_money in my pcoket as an item but i cant use your black market ped in legion because it says i have no black money, and also the washing machines dont do anything

**Comment by TungPunchMe** [comment]
my bank or cash  do not come up when i /bank or /cash /black_money just comes up with $0 in each of them

**Comment by MaDHouSe79** [comment]
i ask the owner of ps, but he closed the topic and not even a response, so i no longer support ps anymore i'm sorry.
