### ISSUE TITLE
SCRIPT ERROR: @qb-inventory/server/main.lua:1703: Attempt to to index a nil value (field 'Stashes' )

### ISSUE THREAD

**Issue by guccihype** [MaDHouSe79/mh-cashasitem#33]
hi im getting an error when trying to use other items in Qb-inventory in game it does nothing (not allowing me to use the item). but i can access other items within the iventory like my gun and i also get this message when trying to use said item
"SCRIPT ERROR: @qb-inventory/server/main.lua:1703: Attempt to to index a nil value (field 'Stashes' ) "

**Comment by MaDHouSe79** [comment]
Hi, did you add this?
https://github.com/MaDHouSe79/mh-cashasitem?tab=readme-ov-file#to-add-in-your-inventory-configlua-file

**Comment by guccihype** [comment]
no i didnt give me a few and ill give u an update on if it fixed

**Comment by guccihype** [comment]
thanks boss man great scrpt btw
