### ISSUE TITLE
PS Inventory can F..off

### ISSUE THREAD

**Issue by AntMars008** [MaDHouSe79/mh-cashasitem#35]
Hi Mads,

Thanks for so quickly adapting your cash-as-item to work with the base QB-inventory. I've had the same experience with those Id10T's at PS, so I know what you're talking about. Let them rot in their own self-importance and arrogance...

Just a bit of clarity on one of your instructions please?

**Check out here, and find min and max. [Amount in Inventory]**

The link doesn't work, so I'm not sure what you mean by this?

**Comment by MaDHouSe79** [comment]
Hi, that part is here,
https://github.com/MaDHouSe79/mh-cashasitem?tab=readme-ov-file#edit-for-item-amount-in-itembox-popup

i was forgot to remove that link 😅

**Comment by AntMars008** [comment]
I did that. It works fine now!
