### ISSUE TITLE
Qustion

### ISSUE THREAD

**Issue by ReazCho** [MaDHouSe79/mh-cashasitem#38]
I am using qb-invenory witch is mising app.js and index.html and ps-hud and it wont work , pls help

**Comment by ReazCho** [comment]
its just show -0 and dont take my money and dont show how many cash i have

**Comment by MaDHouSe79** [comment]
Unfortunately I no longer support any PS scripts because they are too lazy to change anything in their script, so I have decided to no longer support PS at all.
