### ISSUE TITLE
SCRIPT ERROR: @qb-inventory/server/main.lua:1713: attempt to index a nil value (field 'Stashes')

### ISSUE THREAD

**Issue by Damiryeee** [MaDHouSe79/mh-cashasitem#39]
SCRIPT ERROR: @qb-inventory/server/main.lua:1713: attempt to index a nil value (field 'Stashes')

**Comment by MaDHouSe79** [comment]
read this:
https://github.com/MaDHouSe79/mh-cashasitem?tab=readme-ov-file#to-add-in-your-inventory-configlua-file

**Comment by Damiryeee** [comment]
Nice man thank you
