### ISSUE TITLE
RE: ISSUE WITH CASH 

### ISSUE THREAD

**Issue by CollapsedLegacy** [MaDHouSe79/mh-cashasitem#4]
Hi,

I'm trying to use a different inventory system as my whole server is setup for qb-inventory and I don't want to change atm, I have an issue where when I go to give cash to another player it doesn't give them cash, it doesn't deduct from my account either. also with my qb-banking when I withdraw from an atm it doesn't add cash

**Comment by MaDHouSe79** [comment]
If you want to use this script with other inventories than the dependened inventory you have to make it work your self.

This script works with every other script bank/atm/crime that uses the cash/blackmoney system from qbore, 
cause it's made as default as possible and only if you use my mh-inventory that is also the dependencie of this script.
and if you ready want to use it you have to see how i did it in my inventory and do the same in your inventory and I'm not going to do that sorry.
