### ISSUE TITLE
when i drop money or blackmoney it doesnt leave my inventory

### ISSUE THREAD

**Issue by MooseGaming24** [MaDHouSe79/mh-cashasitem#40]
when i drop money or blackmoney it doesnt leave my inventory instead it just reappears into my inventory as if it was not removed.

**Comment by MaDHouSe79** [comment]
read the readme.md file cause it's not a copy past script, you also need to edit your inventory server file for this.

**Comment by MooseGaming24** [comment]
yeah i understand that but i might have missed one of the things that I needed to put in.

**Comment by MaDHouSe79** [comment]
> yeah i understand that but i might have missed one of the things that I needed to put in.

try to follow the entire readme, if you go through it carefully it should work
