### ISSUE TITLE
Undefinedx

### ISSUE THREAD

**Issue by Damiryeee** [MaDHouSe79/mh-cashasitem#42]
When i recieve an item its says "Undefinedx"

**Comment by Damiryeee** [comment]
![t](https://github.com/MaDHouSe79/mh-cashasitem/assets/165581790/ac1937de-3e61-4280-b4da-8bb3ff30a196)

**Comment by MaDHouSe79** [comment]
read this part:https://github.com/MaDHouSe79/mh-cashasitem?tab=readme-ov-file#edit-for-item-amount-in-itembox-popup
and check the Example. you need to edit your server for this.

**Comment by Damiryeee** [comment]
The code is already replaced

**Comment by MaDHouSe79** [comment]
if you get Undefined than you did not edit your server in all scripts that uses that trigger add and remove like the example.
