### ISSUE TITLE
NEW QB-INVENTORY

### ISSUE THREAD

**Issue by Zack3267** [MaDHouSe79/mh-cashasitem#44]
Will this work for the new qbcore inventory? We are working to update our server in the coming few days. We really love this script and want to continue to use it but I want to be sure it will not cause issues with the server. If it is not is there plan to make it available soon for the new inventory system?

**Comment by WPinzonDev** [comment]
3 days ago he uploaded a folder called README, which has instructions and comments related to the new inventory system.

**Comment by MaDHouSe79** [comment]
for now its only for the old qb inventory, maby i will update it later on.
