### ISSUE TITLE
No money can be stacked

### ISSUE THREAD

**Issue by elnexorp** [MaDHouSe79/mh-cashasitem#45]
When I enter the inventory and right click on the pile of money, it automatically leaves 1 dollar on the ground. If I then try to put it back together with the others it does not (and the amount shown by the single dollar goes from 1 to 0, but the total amount of the pile does not increase).

However, if before doing anything, I move the pile of money to any other box in the inventory, everything works perfectly.

I am unable to detect where the error is, so I open the issue to see if you can help me a little.

**Comment by MaDHouSe79** [comment]
this scripts only works on the old qb-inventory not the new one.
