### ISSUE TITLE
Small problem - how to fix?

### ISSUE THREAD

**Issue by AntMars008** [MaDHouSe79/mh-cashasitem#46]
Hi Madhouse,

I use old qb-inventory, and every time I open my inventory, the below happens:
![image](https://github.com/user-attachments/assets/aa9fd27d-fb54-48ce-b82f-cf3253dcab8d)
It looks like my cash and black money is removed (all of it) and then returned to my inventory.
Additionally, when I buy something, all my money is removed and the balance is returned after the item cost has been deducted. See below:
![image](https://github.com/user-attachments/assets/ec75a018-34d3-4dd6-ad56-90e4a1ebb31b)
When I turn off 'useItemBox', I don't see anything, but I do want to see the money being transferred.
I guess I did something wrong with the integration with qb-inventory (maybe the updateTrigger?), so any pointer in the right direction would be appreciated.

**Comment by MaDHouSe79** [comment]
Hi, the right point is to update your old qb-inventory, cause you are out of date.
