### ISSUE TITLE
Errors in F8

### ISSUE THREAD

**Issue by FeaRN30N** [MaDHouSe79/mh-cashasitem#48]
![image](https://github.com/user-attachments/assets/60874818-c3f1-492e-b8b0-bb7f5eef6adc)

So i followed all the steps in detail, from start to finish with a fresh install of QBcore itself, and when i do that this happens every time, clueless on how to fix if theres any way you can help please let me know!

**Comment by MaDHouSe79** [comment]
that this is not F8 but server console ;) ill take a look at it.

issue if fixed.

**Comment by FeaRN30N** [comment]
Definitely console lol. Was Hella tired when I did it lol. Should I re download an give it a try?

**Comment by MaDHouSe79** [comment]
> Definitely console lol. Was Hella tired when I did it lol. Should I re download an give it a try?

yes you need to download a new one ;)

**Comment by FeaRN30N** [comment]
Awesome thank you will do after work and let you know 😀

**Comment by FeaRN30N** [comment]
sorry to bug you, now im getting this error in console
![image](https://github.com/user-attachments/assets/494d2497-94e8-4ff5-993b-5fc2000b0bd4)

**Comment by MaDHouSe79** [comment]
Check: https://github.com/MaDHouSe79/mh-cashasitem/blob/main/readme/qb_inventory.md#example-servercfg

**Comment by MaDHouSe79** [comment]
Oops i see it sorry i change it now

**Comment by MaDHouSe79** [comment]
i fix it, download a now one 😄

**Comment by FeaRN30N** [comment]
Awesome everything is working well!
