### ISSUE TITLE
Item dupe

### ISSUE THREAD

**Issue by Flexiboi** [MaDHouSe79/mh-cashasitem#49]
QB inventgoy version 2.0.0
Cashasitem latest version

The money alwyas gets added in the hotbar slot.
Whenever I move the money 1 space down and drag an other item in that old slot of the money and close / open the inventory it dupes the item.

Any fixes for it?

**Comment by Flexiboi** [comment]
Temp fixed it by adding extra slots in the inventory for each cashitem (So they get added into that slot only) and canceling it when you try to drag other stuff to it

**Comment by MaDHouSe79** [comment]
Sorry for the late reaction, but the script is updated, did you already update?

**Comment by Flexiboi** [comment]
Dope
Just updated and works perfectly! ❤

Legend!
