### ISSUE TITLE
Money Issue v2

### ISSUE THREAD

**Issue by CollapsedLegacy** [MaDHouSe79/mh-cashasitem#5]
I've decided to move to your inventory, but when I drop the cash out of my inventory, it doesn't remove it from my account and I open the inventory back up and it just appears!

**Comment by CollapsedLegacy** [comment]
The inventory stops me from using my petrolcan so I have stopped using it. Is there any chance you can provide me the exports i'd need to make it work with either quasar inventory or qb-inventory please :)

**Comment by MaDHouSe79** [comment]
why does the petrolcan not work? cause that has noting to do with the inventory then only the UseItem part, and that is the server side UsableItem Function Callback that triggers the client side for the fuel script, so where is the issue in the inventory at this point? 😉

**Comment by CollapsedLegacy** [comment]
Im not exactly too sure tbh lol. I used this and it doesn't work but the 1.2.4 version of qb-inventory works but 1.2.0 doesn't

**Comment by MaDHouSe79** [comment]
go to the client part at line 691

change this
```lua
if weaponName == "weapon_fireextinguisher" then
```
to this
```lua
if weaponName == 'weapon_petrolcan' or weaponName == 'weapon_fireextinguisher' then
```

**Comment by CollapsedLegacy** [comment]
didn't work :(

**Comment by MaDHouSe79** [comment]
thats the only diffend between the 2 inventories, cause most of the code is the same, so how can it not work? 😃

**Comment by CollapsedLegacy** [comment]
I'm not too sure tbh. I tried to make it work with both inventories but neither work. Any chance you can give me some advice to make it to qb-inventory or quasar-inventory either or?

**Comment by CollapsedLegacy** [comment]
In the video https://www.youtube.com/watch?v=sWYkV-PeqU4 - you provide - it's qb-inventory

**Comment by MaDHouSe79** [comment]
if you look at 
https://github.com/MaDHouSe79/mh-inventory/blob/622b990070a44935a08b90da67ea4d8da26776ae/server/main.lua#L1550

you see triggers like this:
```lua
TriggerEvent('mh-cashasitem:server:updateCash', src, fromItemData, fromAmount, "remove", false)
```
you need to do the same for your inventory or the one you want to use and is not encypted.

**Comment by CollapsedLegacy** [comment]
Could you elaborate if you don't mind? Am I just copying that code?

**Comment by CollapsedLegacy** [comment]
found one of your old branches and copied and replaced the code. fingers crossed it works

**Comment by CollapsedLegacy** [comment]
So mate, I got it to work, only thing is that when I try and give cash, it doesn't do anything and doesn't take cash out of my account

**Comment by CollapsedLegacy** [comment]
Also when I receive cash no cash goes into my inventory or account

**Comment by CollapsedLegacy** [comment]
its the same when I try to give myself cash as an item via /giveitem. it doesn't work. But doing /givemoney 1 cash does.

**Comment by CollapsedLegacy** [comment]
https://medal.tv/games/gta-v/clips/1BiEOHmz7ZlgNt/d1337FazFZL2?invite=cr-MSw2SkQsMjAzMTQ0NjQ1LA

**Comment by MaDHouSe79** [comment]
you can not just copy past that wil not work, you need to see where every trigger is if you dont put it on the right spot it wil not work

also i don't have quasar-inventory, and that inventory is encypted right? so i can't edit it.


Edit: i try to see why the fuel is not working

A i see it does not take it in his hands

**Comment by CollapsedLegacy** [comment]
Hey again thanks for quick reply. I'M using QB-INVENTORY V1.2.4 (latest). All I need to fix now is just the give to player. is there a trigger that can make that work by chance?

**Comment by MaDHouSe79** [comment]
well first i checked the mh-inventory for the fuel but on my side it works, i can use the weapon_petrolcan and refill my vehicle.

To use this you need to put it on a 1 to 5 slot and press the number to use it, it will span in and you walk to the vehicle tank and you get a text with pess E to refill, there is no usable item trigger when you drag it to use so use the number slots from 1 to 5

**Comment by CollapsedLegacy** [comment]
I didn't like having to do that unfortunately

**Comment by CollapsedLegacy** [comment]
and tried and it didnt work

**Comment by MaDHouSe79** [comment]
i edit the mh-inventory and you can now dubbleclick the item to use it, you only need to download a new mh-inventory 😉

**Comment by CollapsedLegacy** [comment]
Ok and the give cash to player? I still really want to use qb-inventory as I don't like ps-inventories look

**Comment by MaDHouSe79** [comment]
You also need to change this in shared items.

you need to set useable to true, and this only works if you restart the server.

```lua

    -- Miscellaneous
    ['weapon_petrolcan']                = {['name'] = 'weapon_petrolcan',                  ['label'] = 'Petrol Can',                ['weight'] = 1000,         ['type'] = 'weapon',     ['ammotype'] = 'AMMO_PETROLCAN',           ['image'] = 'weapon_petrolcan.png',          ['unique'] = true,         ['useable'] = true,      ['description'] = 'A robust liquid container made from pressed steel'},
    ['weapon_fireextinguisher']         = {['name'] = 'weapon_fireextinguisher',           ['label'] = 'Fire Extinguisher',         ['weight'] = 1000,         ['type'] = 'weapon',     ['ammotype'] = nil,                        ['image'] = 'weapon_fireextinguisher.png',   ['unique'] = true,         ['useable'] = true,      ['description'] = 'A portable device that discharges a jet of water, foam, gas, or other material to extinguish a fire'},
    ['weapon_hazardcan']                = {['name'] = 'weapon_hazardcan',                  ['label'] = 'Hazardous Jerry Can',       ['weight'] = 1000,         ['type'] = 'weapon',     ['ammotype'] = 'AMMO_PETROLCAN',           ['image'] = 'weapon_hazardcan.png',          ['unique'] = true,         ['useable'] = true,      ['description'] = 'Weapon Hazardcan'},
```

**Comment by CollapsedLegacy** [comment]
Already done that

**Comment by MaDHouSe79** [comment]
for the style check if you can replace the old style.css and the index.html file from the default qb-inventory and replace in mh-inventory and see if it works.

**Comment by CollapsedLegacy** [comment]
That most likley wont work but ill try shortly

**Comment by MaDHouSe79** [comment]
no that does not work ;) uhm dammed..

ok if you only change the css file it does work, you only need to remove the image

**Comment by CollapsedLegacy** [comment]
What's it look like though? Like qb-inventory or more like ps? Is there no way to just make it so the give cash works?

**Comment by MaDHouSe79** [comment]
no it does not look good with the images in the inventory slots from 1 to 5

**Comment by CollapsedLegacy** [comment]
So any chance to just fix the giving cash issue?

**Comment by MaDHouSe79** [comment]
Try this default qb-inventory https://we.tl/t-AiynQuPuK5

**Comment by CollapsedLegacy** [comment]
Just used your inventory and it doesnt work with the cash. I tested and it doesn't update the cash. I just need to get help now with the give person cash with qb-inventory

**Comment by CollapsedLegacy** [comment]
Is that qb-inventory meant to fix the giving cash issue?

**Comment by CollapsedLegacy** [comment]
It didnt fix the giving cash issue unfortunately ;(

**Comment by CollapsedLegacy** [comment]
@MaDHouSe79 I'm thinking that there may be a way to create an NUICallback but I'm not exactly sure and unfortunately GPT doesn't help ;(. Is there anyway for this or am I stuffed? I really want to knock this issue over.

**Comment by MaDHouSe79** [comment]
I don't know which one you are using now but not al branches works, cause that where testing scripts, the one that is online now has the option to give money from the inventory so I don't know which one you are using. and why it does not work cause its the same code for all other items.

**Comment by CollapsedLegacy** [comment]
Can you provide me the correct branch? I'm using the main branch and its qb-inventory v 1.2.4

**Comment by MaDHouSe79** [comment]
send me the one you use, cause this is going noware and is a wast of time :)

**Comment by CollapsedLegacy** [comment]
here it is. https://drive.google.com/file/d/134SZ63PJjc1uYgCoWg22upYdXVE_yioL/view?usp=sharing

**Comment by MaDHouSe79** [comment]
uhm, in your inventory in the server file find the trigger
inventory:server:GiveItem

and replace the code with this code and see if that works, i cant test it cause i'm alone at my server.

```lua
RegisterServerEvent("inventory:server:GiveItem", function(target, name, amount, slot)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    target = tonumber(target)
    local OtherPlayer = QBCore.Functions.GetPlayer(target)
    local dist = #(GetEntityCoords(GetPlayerPed(src)) - GetEntityCoords(GetPlayerPed(target)))
    if Player == OtherPlayer then
        return QBCore.Functions.Notify(src, Lang:t("notify.gsitem"))
    end
    if dist > 2 then
        return QBCore.Functions.Notify(src, Lang:t("notify.tftgitem"))
    end
    local item = GetItemBySlot(src, slot)
    if not item then
        QBCore.Functions.Notify(src, Lang:t("notify.infound"));
        return
    end
    if item.name ~= name then
        QBCore.Functions.Notify(src, Lang:t("notify.iifound"));
        return
    end
    if amount <= item.amount then
        if amount == 0 then
            amount = item.amount
        end
        if RemoveItem(src, item.name, amount, item.slot) then
            TriggerEvent('mh-cashasitem:server:updateCash', src, item, amount, "remove", true)
            if AddItem(target, item.name, amount, false, item.info) then
                TriggerEvent('mh-cashasitem:server:updateCash', target, item, amount, "add", true)
                TriggerClientEvent('inventory:client:ItemBox', target, QBCore.Shared.Items[item.name], "add")
                QBCore.Functions.Notify(target,
                    Lang:t("notify.gitemrec") .. amount .. ' ' .. item.label .. Lang:t("notify.gitemfrom") ..
                        Player.PlayerData.charinfo.firstname .. " " .. Player.PlayerData.charinfo.lastname)
                TriggerClientEvent("inventory:client:UpdatePlayerInventory", target, true)
                TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items[item.name], "remove")
                QBCore.Functions.Notify(src,
                    Lang:t("notify.gitemyg") .. OtherPlayer.PlayerData.charinfo.firstname .. " " ..
                        OtherPlayer.PlayerData.charinfo.lastname .. " " .. amount .. " " .. item.label .. "!")
                TriggerClientEvent("inventory:client:UpdatePlayerInventory", src, true)
                TriggerClientEvent('qb-inventory:client:giveAnim', src)
                TriggerClientEvent('qb-inventory:client:giveAnim', target)
            else
                AddItem(src, item.name, amount, item.slot, item.info)
                TriggerEvent('mh-cashasitem:server:updateCash', src, item, amount, "add", true)
                QBCore.Functions.Notify(src, Lang:t("notify.gitinvfull"), "error")
                QBCore.Functions.Notify(target, Lang:t("notify.giymif"), "error")
                TriggerClientEvent("inventory:client:UpdatePlayerInventory", src, false)
                TriggerClientEvent("inventory:client:UpdatePlayerInventory", target, false)
            end
        else
            QBCore.Functions.Notify(src, Lang:t("notify.gitydhei"), "error")
        end
    else
        QBCore.Functions.Notify(src, Lang:t("notify.gitydhitt"))
    end
end)
```

**Comment by CollapsedLegacy** [comment]
You're the king! Thanks heaps mate!
