### ISSUE TITLE
Inventory errors not opening inventory 

### ISSUE THREAD

**Issue by elkie1991gaming** [MaDHouSe79/mh-cashasitem#52]
There is an issue after following the read me that the inventory doesn't open and causes errors server side 

https://cdn.discordapp.com/attachments/1231308697393696789/1295422782783357040/Screenshot_2024-10-14_090725.png?ex=671486bb&is=6713353b&hm=e2acda612f9597ad757ffc9f562c035a31df7c4718cabf95e0f758f9900a6d83&

**Comment by MaDHouSe79** [comment]
code is already updated ;)

**Comment by elkie1991gaming** [comment]
Thank you
