### ISSUE TITLE
Item box appears when opening inventory.

### ISSUE THREAD

**Issue by arrogantrp** [MaDHouSe79/mh-cashasitem#6]
Have to disable the item boxes because when you open inventory it says "added" & "removed".

Also locales for give item are messed up on mh-inventory, really wished you didn't delete your discord :(

**Comment by MaDHouSe79** [comment]
Discord was barely used, and when I upload something I don't even get a response or a like or anything so I know people like it, but unfortunately that is not the case. and that's why I deleted it.

**Comment by arrogantrp** [comment]
> Discord was barely used, and when I upload something I don't even get a response or a like or anything so I know people like it, but unfortunately that is not the case. and that's why I deleted it.
> 
> to disable the itembox check the config file

Yes I have done that, but now if you deposit or withdraw the box doesn't appear ;)

And brother, it's not all about the likes and attention, you're doing gods work and you have to keep pushing, everyone loves your work...I'm probably your #1 fan haha

**Comment by MaDHouSe79** [comment]
i don't want the attention all i want to know is, if people like stuff yes or no, and by likeing stuff i know people like it, 
and that i don't do stuff for nothing and i don't wast my time on this,
if no one like stuff than it's not really motivated for me, do you understand what i mean with this?
i don't care about the attention. i care about if people like my stuff yes or no thats it.

**Comment by arrogantrp** [comment]
> i don't want the attention all i want to know is, if people like stuff yes or no, and by likeing stuff i know people like it, and that i don't do stuff for nothing and i don't wast my time on this, if no one like stuff than it's not really motivated for me, do you understand what i mean with this? i don't care about the attention. i care about if people like my stuff yes or no thats it.

I know what you mean and how you feel, if you ever want to work together let me know, it would be an honor <3 I'm making something truly amazing

**Comment by MaDHouSe79** [comment]
That depends on what you are making and what I could help you with.

**Comment by arrogantrp** [comment]
> That depends on what you are making and what I could help you with.

I've only been into dev work about a year and a half on and off, so I'm nowhere on your level, but I do have an image and I am able to put that image into the game, so maybe that makes me a dev I don't know, But as for working together to join me as a dev if you're interested, there's not gonna be any heavy load or anything, but you're probably already apart of some other community and I don't want to be rude, but the offer is there, I'm currently doing everything on my own, finished a website etc, if you ever get bored or want to come back to it you know :), I just started working on interactable things, so you can pickup stuff off the wall and things like that, economy is realistic as well, I want to figure out how to add different types of bills and cents, but it's probably gonna have to be the "fiat" way, I have so much on my list haha, invested more into this than I'd like to admit, but your scripts make the city what it is bro, I use a lot of them and getting more added haha
