### ISSUE TITLE
Blackmoney disappears from inventory

### ISSUE THREAD

**Issue by Rodriguez311** [MaDHouSe79/mh-cashasitem#7]
Hey!
Im having a problem now, i give blackmoney to myself but when i open my invetory it disappears 
Any idea what can i do to fix?

**Comment by Rodriguez311** [comment]
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/150092139/26af647d-144b-4404-b55a-6bc2de1cb9b2)
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/150092139/efeab45e-0d48-4954-870e-3141b0d4b8e8)
When i give the blackmoney he appears if i click "Z" button but when i open the full inventory he disappears :x

**Comment by MaDHouSe79** [comment]
Hi,

if you give your self blackmoney do you see a money change on the right top of your screen? 
if not you did not get the blackmoney and thats why it disappears cause the amount of blackmoney stays 0 but you only get an item?
