### ISSUE TITLE
Cash item not showing up in inventory after giving to player

### ISSUE THREAD

**Issue by JD252525** [MaDHouSe79/mh-cashasitem#8]
Cash item not showing up in inventory after giving to player
I'm using your version of QB core inventory
![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/63257881/9b13288e-69ef-4d47-b559-219807cfd3fa)

![image](https://github.com/MaDHouSe79/mh-cashasitem/assets/63257881/6b6379e6-e779-4f88-9212-c803f46ce963)

**Comment by MaDHouSe79** [comment]
Try to use the readme folder for QB -> https://github.com/MaDHouSe79/mh-cashasitem/tree/main/readme, you need a clean inventory from QB or PS to use that.
